<a href="https://colab.research.google.com/github/meryemtetik/Assignment-1/blob/master/Kopie_von_Stats_Assign_(Central_Tendency%26_Dispersion).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [1]:
import numpy as np
from scipy import stats
import pandas as pd

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [2]:
samples = np.random.normal(100,15,1000)
samples

array([100.56867788, 128.48120272,  93.49215262, 123.86928615,
        57.60890876, 107.09650425,  93.48347337,  97.70405495,
       103.69835649, 124.02439333,  83.56160696, 114.36683353,
       107.31457326,  95.08165134,  95.92403288,  99.63298884,
       114.32363917,  91.42799659,  88.60704133,  59.70476132,
        77.18463107, 115.34699444,  99.03099354, 126.20939875,
       119.71232893,  77.87585873,  86.81261119,  89.49608851,
        76.02001565,  83.11799257,  88.66362329,  93.65089078,
        80.41112769,  68.83608957,  91.22697724,  91.93950132,
       111.33829619,  86.95307995,  92.10372639, 109.38891423,
        85.19346388,  67.4384267 ,  65.00662884,  85.7604036 ,
       113.49928651, 100.800222  , 102.48627738, 128.78337938,
        93.43926877,  94.02974258,  71.6494594 ,  89.95192122,
        97.8050775 , 118.82974079,  96.79044338, 103.64101355,
        93.77732003,  83.71038014, 103.78394206,  96.96189442,
       113.55345203, 106.65769761,  78.7696892 , 112.18654546,
        94.7457087 , 101.07845203,  88.22589582,  92.81210419,
        96.84854569,  90.81201033, 108.93387475, 117.58669305,
       109.01304187,  78.73999629, 115.00874236,  95.47642101,
       112.91015741,  95.09565405,  92.16477534, 102.60030826,
       109.09315291,  98.94741162,  90.39868512, 132.77038463,
       127.36896375, 100.08205015,  93.3782957 ,  87.49154603,
       102.11118887, 119.77672548, 141.39706502, 121.32067747,
       103.43971484,  86.12649219,  76.50647321, 100.31194175,
        86.99621439,  90.2886289 ,  93.51416274,  80.98349702,
       102.37955364,  93.49410628,  90.48040515,  87.17366722,
        77.4865822 , 100.12692069,  95.64455141,  92.33113582,
        77.73350788, 106.70190646, 113.38138749, 116.21737785,
       110.01854634, 123.32728708, 108.71551535,  88.97912059,
       103.20868195,  82.49360431, 134.23884918,  92.386802  ,
        88.373441  , 120.96483633,  56.55732532, 127.27575299,
        76.07187137,  73.32141097,  87.56305032,  71.34187119,
       121.44897179,  88.57712365,  93.69229641,  71.41103904,
        90.0448016 , 108.31687166, 119.12603731,  95.35364214,
       103.29186364,  91.17755764, 101.18390766,  96.11662163,
       105.86247413, 118.09632635,  83.96949368, 104.62270506,
       109.4274056 ,  97.97275705, 115.16361975,  94.3833294 ,
        64.31628424, 101.19332366, 118.70318693,  93.35233929,
        87.90615871,  77.9393597 , 119.22887487,  74.56345953,
        99.93559463,  85.412763  ,  80.03121565, 118.61713078,
        53.1421176 ,  97.72816477, 116.50035218,  91.10304859,
        97.70234178, 100.71134691, 107.86883634, 111.02660859,
        99.81458289, 119.24297708,  95.13435628, 116.69500465,
        90.60718341,  98.41730498, 111.29276915,  83.32724982,
        83.34569707,  84.13800314, 110.31253796,  74.71895763,
       102.7476409 ,  68.85960062,  98.12548782, 130.78652474,
        76.70178013,  86.67539109, 106.22864771,  86.34316073,
       126.29168618, 109.13754393,  86.97134434, 120.75347305,
       110.82158074,  77.69181887,  72.60964573,  88.82881397,
       118.88969298, 126.44516918,  86.13163383,  97.54818316,
        86.09623957, 102.84104194,  69.52974245,  86.24727508,
       105.76990431,  90.22367949, 100.60342387,  82.17028918,
        78.05296123, 113.3573255 , 121.79817334, 100.16295595,
        98.58613659,  94.10905862, 105.23180533,  59.01550273,
        83.92048645,  98.34770559,  82.13784447,  94.45255022,
        91.447075  , 100.30367124,  89.46490326,  93.00408909,
        67.45257429,  85.42748083,  65.55455849,  59.20697861,
        94.59018966,  96.7815988 , 121.41147402,  78.51237461,
        99.50998495, 102.99886098,  94.69276608, 112.95489493,
       109.75034748,  87.95237882, 100.60638175,  93.7781473 ,
       117.67240013, 113.62160479, 105.0515038 , 103.41705882,
        95.53610555,  89.30564383, 116.22641517, 110.21333637,
       102.68257943, 120.01514991,  81.3334047 ,  79.84301168,
        95.01016707, 112.78672406,  97.37349835,  93.53710869,
        77.28333626, 113.48293132,  79.60207809,  89.68029312,
       109.30231544,  96.59969014,  82.88795932,  90.24377263,
       116.98438625,  81.63437842, 109.56807685,  98.56255077,
        87.53481398,  96.49842893,  86.94737876,  91.15892788,
       106.8880256 , 112.90449029,  93.39870154,  60.14429422,
       106.95024776,  88.70380606, 102.62138686,  94.09411089,
       109.33686326,  67.22087657,  91.29667373,  84.66922258,
        85.43506716, 116.59242926, 119.04244468,  86.17199844,
       104.55697295,  80.99773067, 113.88785631, 110.80169506,
       120.76295854,  86.49641921,  90.10007384,  79.34713286,
        97.31864303,  89.78461216,  92.10927107, 109.55637156,
        84.53131813,  72.13537845,  91.75837976, 114.59781743,
        83.43141089,  87.84861018,  93.88023602,  83.93952102,
       123.18649602, 117.04664382,  74.38159975,  83.32340068,
        99.2996788 ,  99.76472791, 124.65036511, 109.38127541,
        90.55296487,  82.03511143,  96.62097788,  75.29438972,
        70.71499303, 101.00183311, 104.31354834,  69.76399203,
        98.90892419, 106.88615111,  89.86400481,  70.68911515,
       104.78022157, 109.50473545,  89.85520347, 140.21491189,
       105.50375797, 115.55371027, 119.98836498, 111.4499363 ,
       115.67144982,  97.64523885, 105.5888253 ,  93.2207774 ,
       122.06141086,  82.58975621, 109.26941586,  97.66372859,
        91.95373547, 117.07117191,  78.37244907,  92.1727445 ,
       103.07242278, 100.52767265,  97.25695154, 103.24208638,
        83.88016977,  93.76029895, 106.29965729, 124.21773304,
       125.57709328,  91.1565657 , 104.85866737, 110.9827166 ,
       107.48602967,  80.32096215,  94.01685183,  99.23508603,
       112.91371693,  88.91482771,  83.54006024,  92.48312788,
       100.98887429, 123.15535356,  71.45467393, 106.39144635,
       102.01383082, 109.88033343, 100.43320693, 106.06387888,
        87.97594373,  99.18173603,  92.56254599,  79.51345837,
        88.15577323, 109.75149684,  85.95968804,  81.55834811,
        98.48986992,  79.95361337, 117.25764079,  96.94628138,
        98.81544971, 106.46646653, 115.80363336,  68.86136585,
        75.70124244,  79.0956176 ,  65.96027024,  98.34291683,
        98.18159774, 115.91056512,  84.7573007 ,  95.02062566,
       123.05304472,  86.19828448, 109.71626429,  69.21285379,
       103.25907687,  95.15370993,  82.73680265,  92.20183089,
       119.03911723,  85.08894363, 104.96726033,  90.63876644,
        96.32697004, 103.219463  ,  94.27848189,  84.08773609,
       103.25987781, 124.09869845,  87.42066671, 111.68257508,
        91.06888509,  87.29144459, 121.51819121, 120.16826228,
       101.7355669 , 102.4751116 ,  89.86335141,  88.00665463,
       106.81077346, 123.74870332, 123.0047387 ,  90.8835695 ,
       116.6916589 ,  99.94391689, 116.59671333,  77.41026696,
       107.67016132, 116.28985712, 134.78074746, 106.36253631,
       107.97850967, 110.69529061,  81.3471862 , 134.14305629,
        95.72788049, 105.60928639,  83.81596291, 122.38202356,
        94.07634493, 118.13149714, 106.2711691 , 104.08383763,
       112.86064959,  64.78478288,  99.06552209,  84.92451235,
        90.22806323, 112.75210774, 120.99843193, 100.08910349,
       114.90580422, 129.73897371, 123.84381872,  83.08405308,
       102.20382285,  94.36943626, 113.68400915, 112.19341042,
       119.65207973,  93.22237236,  89.68301261,  91.59498635,
       113.26518897, 124.46145879, 108.91902964,  94.51781899,
       104.61450908, 119.95052594,  82.84270729, 102.49258259,
        82.23589838, 104.65149453, 116.50217784,  97.58666158,
       115.21224717, 108.15087587,  90.6936001 , 106.34799764,
       113.64696615, 110.8539813 , 104.98972284, 101.20417516,
       105.99807224,  94.34792247, 107.51291439, 119.85535924,
        86.0480262 ,  88.55226141, 103.58625755, 105.92771697,
        93.45774051,  80.49235798, 104.76708033,  86.22416222,
        80.61188876, 108.04099615, 106.67202822, 115.51637692,
        74.37966244, 114.35533278, 110.80616938, 123.99981321,
        90.34046644,  95.52060598, 119.07111893,  89.91869827,
        95.23626376,  87.39642339,  80.43129655,  84.18578181,
        98.64298626,  76.10013674, 108.8740474 , 104.37287627,
        90.40026578,  90.485933  ,  79.87591423, 102.76396782,
       111.28370643,  92.0054578 ,  93.22828124,  95.33354694,
       121.34960483,  75.60827807, 117.25759622, 100.29995725,
       118.37438452,  92.13929451,  89.75770957, 120.63181986,
       106.39202021, 102.77575923, 119.67741205,  92.96086425,
       111.74967122, 102.1363    ,  76.97161203,  77.42503881,
       137.3183853 ,  96.41332266, 101.58199573, 104.40482734,
       114.6430465 , 101.13591422,  90.64770239, 103.08455388,
        94.28592916,  84.05226633,  86.90231133, 113.50523713,
        81.80841776, 115.40053519, 102.334545  , 110.423347  ,
        98.07881672, 124.32111252, 109.18944999,  90.74741066,
       122.95425824, 126.80794252,  89.82992392,  90.05994346,
       123.77683414,  99.93928767,  93.93288753,  81.26011979,
       108.48752045,  75.39516941,  99.51577941, 104.36209282,
       111.53020667, 105.82413052,  81.0603244 , 125.56096781,
        86.46669216,  73.48334158, 103.77646453, 100.28741335,
        78.89451855,  71.09918408, 151.92136139,  84.06083486,
        95.72273512, 119.15895474,  98.99761001, 102.27692314,
       127.33033511, 127.76820783, 110.41624645, 109.1149051 ,
       133.36353808,  75.98640128, 113.20368484,  78.69831888,
        99.05707781,  92.83223229,  68.04040147,  98.29300336,
        87.31253493,  94.35990978, 118.59434959,  92.69845286,
       113.89073513, 108.0131656 ,  83.71303162,  97.56779937,
        94.26925339, 123.4347885 , 115.02005151, 108.72365319,
        96.2601711 , 115.70905092, 107.77779986,  77.0341464 ,
        92.41955768,  96.84929377,  92.25168962,  87.07205641,
       100.11933408, 101.24994825,  99.07000464, 104.33060295,
        85.19895249, 118.40611534,  94.39704419,  85.1575728 ,
        90.66095065,  86.12098339,  99.21281495, 108.53988329,
       105.61889535,  74.03544738,  91.91488982, 112.22183677,
       125.12475515,  90.31993219,  84.20279658,  99.22493609,
        92.61808333,  98.90586862, 112.51268231, 109.51161934,
       112.83526559,  97.24509423,  94.62631   ,  98.36385156,
        86.46999378, 103.36148772, 110.49198948,  89.66681317,
       108.73969217, 141.18650165, 100.19613217,  87.24921114,
        95.12327404,  96.21571729,  95.13383619, 120.38930533,
       110.59438488, 111.68124043, 106.54913758,  67.36994392,
       112.69456834,  96.53458051, 110.79761045,  91.21340101,
        96.4016583 ,  79.36555055,  76.10548063, 102.91632168,
        87.21491832,  74.27518092,  77.14588666,  87.15407719,
       118.96475513, 114.32701624, 109.75969864,  86.70717062,
        93.95519029, 105.15978229,  91.56206274,  97.56838998,
       108.01979528, 110.7829113 ,  91.5929748 , 115.33595292,
       117.55227651, 108.25929276, 104.6052313 , 114.06762682,
        92.3672757 , 114.34077168, 105.84248523, 101.19469163,
        82.38519903,  56.87298922, 107.4980326 , 129.16799007,
        76.40096345, 107.64142057,  80.44971782,  93.04748559,
        94.62485374, 108.53632732, 105.03102282,  97.36011395,
        88.03124917, 104.88351158, 101.98309809, 115.40768745,
        74.83179115,  97.88255263, 122.95005533,  83.58530434,
        92.71856304,  89.28716391,  95.61442127,  76.48272311,
       106.44875255,  93.12318738,  78.66727437,  97.89687487,
        98.5712407 ,  83.63596275, 107.30046806, 108.10697396,
       124.01058771,  94.97945964,  96.24760495,  98.56140527,
        89.34657858,  84.11324648,  84.03472623, 125.70537375,
       124.07600127,  93.32306235, 101.49504108,  97.18604551,
       103.47964844,  79.82611633,  70.72635015, 121.97040016,
        83.34904812, 102.52064494, 102.38387114,  98.42908789,
       106.06542647, 113.78269497, 102.83602776,  86.52675748,
       129.3508166 , 117.53997607, 112.59310124, 101.12859196,
       104.86366371, 132.57897005,  89.47353979, 110.87571194,
       105.08299995,  60.39684556,  86.44886516,  87.65860759,
       119.59062204, 104.65064518,  99.93104366, 123.51015863,
        84.34630851, 120.64263017, 106.05917528,  85.62642187,
       101.75089767, 123.4976235 , 114.95101731, 109.60733578,
        98.77107665,  98.24480404, 111.51150012,  80.5108686 ,
        96.03778811, 125.63357502,  93.81753654,  94.12706338,
        95.78963471, 112.11435289, 116.6658491 , 103.32359987,
        65.23820618,  82.5946446 ,  91.27979452,  81.1152101 ,
        71.02508212, 108.29665027, 103.54456534, 101.1701627 ,
       118.60915331, 116.31898958, 113.94753483, 101.23791918,
       112.02742829,  94.30543284,  90.88152759, 104.6571098 ,
       107.44800287,  93.58808115,  95.82807712,  84.9883993 ,
        81.55021376, 107.4228064 ,  95.80468459, 101.95536971,
        96.33568438,  93.09245   , 114.54586793, 107.47151349,
       113.4986638 ,  86.48374089, 117.36704084,  91.09135385,
       105.41577384, 134.71586946,  96.98106023,  94.28418662,
        93.89454388, 126.72994497,  88.41312785,  94.75177972,
       112.10624044, 104.47458216,  99.4932249 , 118.15801632,
       130.09844863, 109.37653463,  89.06319395,  81.56977897,
       101.48113288,  96.56991947, 104.77355907,  86.33841909,
       104.54138689,  80.65394204,  96.98870336, 103.7945994 ,
       109.45416696, 100.90238529, 129.19484988, 116.91632747,
       119.21617437,  88.20057705,  79.81302445,  78.09974815,
        86.8432959 ,  91.92888608,  98.89968363,  96.20022681,
       107.81429982,  91.34689   , 109.31515698, 111.18070287,
        89.85451436,  68.01862788, 106.3304022 ,  91.08799395,
        96.26912912,  98.48246528,  91.40026812,  78.43610136,
        96.07334149,  67.99513573, 104.00743001,  94.16986398,
        93.24993061,  91.93030822,  96.6881743 ,  86.35636796,
        55.75736015,  99.55086761,  88.07182029, 126.25498721,
       109.24317331, 113.98047826,  96.55060947, 107.03736351,
       104.2958217 , 108.74520236, 100.03925865, 105.84035459,
       119.06997732, 110.78840193,  97.0842717 ,  88.23708998,
        74.32826832,  94.25300495,  97.76185754, 100.15447036,
       103.50417538, 109.9749204 ,  83.96644084, 116.44222744,
        90.31498898, 121.13246109,  82.42746168,  79.31608379,
       104.60187001, 103.05653661,  76.34851115,  69.83354887,
       101.08118641, 104.25460867,  93.66380284,  80.58244009,
       106.10225873, 103.97173906,  98.39882251, 118.23366199,
        89.60451406,  98.77252933,  79.9104224 , 131.52070688,
       126.38785595,  90.80114458,  99.22218479, 105.68107231,
       109.16395409, 110.28403257, 125.30104407,  80.58883756,
       102.54172008, 147.60072401,  71.80066737, 100.54839204,
       126.58186003,  87.73182574, 102.48825688, 105.15497443,
        93.25714108,  69.64436125, 107.48032684,  87.1641633 ,
        92.46219632,  70.00686132,  78.5912936 , 103.29419926,
        93.44171739, 100.5532179 ,  88.14228512,  89.86329481,
        85.62674936, 111.43709876,  98.70738353, 121.42790376,
        93.97301465, 101.76673993,  90.13519996,  95.48662946,
        84.06114744,  86.48193149, 108.63296988, 109.00607955,
       111.86632358,  93.30428847, 108.03242349,  81.30847341,
       127.63679724, 132.17975911, 130.29936732,  94.69937279,
       100.64222366, 121.99199338,  80.79404237,  90.7713216 ,
        85.9904305 ,  82.98471849,  98.33286387, 100.44302166,
       104.21232518,  88.60179532, 108.48035223,  85.52626486,
        89.46293654, 100.86475903,  92.00047656, 102.49635994,
       117.85741491,  74.72706386,  82.2336092 , 121.62569164,
       104.03929295, 103.54680576,  91.30946951,  85.91135883])

Compute the **mean**, **median**, and **mode**

In [3]:
mean = np.mean(samples)
median =np.median(samples)
mode =stats.mode(samples)
print(mean)
print(median)
print(mode)

98.90616595010475
98.48616760012355
ModeResult(mode=array([53.1421176]), count=array([1]))

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [4]:
min = np.min(samples)
max = np.max(samples)
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = stats.iqr(samples)    # or   iqr = q3-q1
print(min)
print(max)
print(q1)
print(q3)
print(iqr)

53.14211759608388
151.92136139253392
88.59562739894758
109.30552582379784
20.709898424850252

Compute the **variance** and **standard deviation**

In [5]:
variance = np.var(samples)
std_dev = np.std(samples)
print(variance)
print(std_dev)

233.9436495638488
15.29521655825274

Compute the **skewness** and **kurtosis**

You can use [`scipy.stats.skew`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html) and [`scipy.stats.kurtosis`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html)

In [6]:
from scipy.stats import kurtosis, skew
from scipy import stats
skewness = skew(samples)    #or   skewness = scipy.stats.skew(samples) ??
kurtosis = kurtosis(samples)    #or kurtosis = scipy.stats.kurstosis(samples) ??
print(skewness)
print(kurtosis)

0.033245828113820125
-0.047631407289335126

## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [7]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [8]:
y = np.array([np.random.randint(0, 100) for i in range(10)])   #??????????
y   #or y = np.array(np.random.randint(0,100,10))

array([88, 67, 16, 87, 14, 72, 48, 31, 69, 41])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [9]:
r = np.corrcoef(x, y)
r

array([[ 1.        , -0.26359145],
       [-0.26359145,  1.        ]])

## Pandas Correlation Calculation

Run the code below

In [10]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [11]:
r = stats.pearsonr(x, y)
r

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [12]:
rho = stats.spearmanr(x, y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [13]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [14]:
tips = sns.load_dataset("tips")
tips.head

<bound method NDFrame.head of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [15]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [16]:

tips.corr()

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000